server:
  host: localhost:8080

spring:
  jpa:
    show-sql: true

    properties:
      hibernate:
        ddl-auto: create-drop
        "[format_sql]": true

  image:
    path: /var/img/test

# Security
security:
  jwt:
    secret: loooooooooooooooooooooooooooongsecuritytest
